# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "authors-app"
    scrape_interval: 10s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['authors:8080']
  - job_name: "books-app"
    scrape_interval: 10s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: [ 'books:8080' ]
  - job_name: "customers-app"
    scrape_interval: 10s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: [ 'customers:8080' ]
  - job_name: 'proxy'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['proxy:8082']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgresql-exporter:9187']